
package TwitDegrees.Presentation.Api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ITwitter", targetNamespace = "TwitDegrees.Web.Api")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ITwitter {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetUserGraphML", action = "TwitDegrees.Web.Api/ITwitter/GetUserGraphML")
    @WebResult(name = "GetUserGraphMLResult", targetNamespace = "TwitDegrees.Web.Api")
    @RequestWrapper(localName = "GetUserGraphML", targetNamespace = "TwitDegrees.Web.Api", className = "TwitDegrees.Presentation.Api.GetUserGraphML")
    @ResponseWrapper(localName = "GetUserGraphMLResponse", targetNamespace = "TwitDegrees.Web.Api", className = "TwitDegrees.Presentation.Api.GetUserGraphMLResponse")
    public String getUserGraphML(
        @WebParam(name = "name", targetNamespace = "TwitDegrees.Web.Api")
        String name);

}
